### PR TITLE
Fix + Optimizing TLS detection via half-handshake

### LINKED ISSUE #1572: fix: TLS detection support
### Current Behavior:
Naabu currently reports all TCP ports as tls: false, even for ports that explicitly support TLS/SSL like HTTPS (port 443). This happens because naabu only performs TCP connect scans without attempting TLS handshakes to verify if a service actually supports TLS encryption

Example output:
```$ naabu -host hackerone.com -j
{"host":"hackerone.com","ip":"172.64.151.42","timestamp":"2025-10-29T07:13:20.340296Z","port":443,"protocol":"tcp","tls":false}  # WRONG - should be true
```

### Expected Behavior:
Naabu should accurately detect whether TCP ports support TLS
```$ naabu -host hackerone.com -j
{"host":"hackerone.com","ip":"172.64.151.42","timestamp":"2025-10-29T07:13:20.340296Z","port":443,"protocol":"tcp","tls":true}  # CORRECT
```

### Steps To Reproduce:
1. Run naabu against any HTTPS-enabled service: `naabu -host hackerone.com -j -debug`
2. Observe that port 443 shows tls: false even though hackerone.com serves HTTPS
3. Verify manually with OpenSSL: `openssl s_client -connect hackerone.com:443 -servername hackerone.com`
4. This succeeds, confirming TLS is available but naabu doesn't detect it.

### PR DESCRIPTION
**Pull request by Mzack9999**
Closes #1572

## Summary by CodeRabbit

* **New Features**
  * Added automatic TLS detection for TCP connections during scans. Detection is disabled by default and can be enabled via environment configuration; results are recorded per connection.

* **Chores**
  * Updated several internal library dependencies to newer patch versions.

### CODE REVIEW

File: pkg/scan/scan.go [hunk 1]
```diff
@@ -385,6 +388,144 @@ func GetInterfaceFromIP(ip net.IP) (*net.Interface, error) {
...
+
+	if n < 5 {
+		return false
+	}
+
+	// check content type (0x15=Alert, 0x16=Handshake)
+	contentType := buffer[0]
+	if contentType != 0x15 && contentType != 0x16 {
+		return false
+	}
```
Comment (dwisiswant0) [inline pkg/scan/scan.go]: Wait, this returns `true` if the handshake doesn’t succeed, intended?

File: pkg/scan/scan.go [hunk 2]
```diff
@@ -385,6 +388,144 @@ func GetInterfaceFromIP(ip net.IP) (*net.Interface, error) {
...
+
+	// if handshake, check for ServerHello (0x02)
+	if contentType == 0x16 && n >= 6 {
+		if buffer[5] == 0x02 {
+			return true
+		}
+	}
+
+	return true
```
Comment (dwisiswant0) [inline pkg/scan/scan.go]: "if I got any data from the server, I’ll say this is TLS", which is too loose.

**Review by dwisiswant0 — CHANGES_REQUESTED** [review]

File: pkg/scan/scan.go (hunk 1 above)
Comment (Mzack9999) [reply pkg/scan/scan.go]: It's intentional, an error during protocol negotiation means anyway that TLS is supported

File: pkg/scan/scan.go (hunk 2 above)
Comment (Mzack9999) [reply pkg/scan/scan.go]: it's a catch all, if we reach this point, most of tls bytes pattern response should have matched
