### PR TITLE
fix printing issue with hostname in passive mode

### LINKED ISSUE #787: printing issue with hostname in passive mode
### Naabu version:
latest

### Current Behavior:
```console
naabu -host projectdiscovery.io -ec -silent -passive

104.26.7.152:2087
104.26.7.152:8443
104.26.7.152:8880
104.26.7.152:80
104.26.7.152:443
104.26.7.152:2082
104.26.7.152:2083
```

### Expected Behavior:
```console
naabu -host projectdiscovery.io -ec -silent -passive

projectdiscovery.io:80
projectdiscovery.io:443
projectdiscovery.io:2082
projectdiscovery.io:2083
projectdiscovery.io:2087
projectdiscovery.io:8443
projectdiscovery.io:8880
```
### Steps To Reproduce:
`naabu -host projectdiscovery.io -ec -silent -passive`

### Anything else:
Related change - https://github.com/projectdiscovery/naabu/pull/767

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #787.

before:
```console
$ go run . -host projectdiscovery.io -ec -silent -passive

104.26.7.152:2087
104.26.7.152:8443
104.26.7.152:8880
104.26.7.152:80
104.26.7.152:443
104.26.7.152:2082
104.26.7.152:2083
```

after:
```console
$ go run . -host projectdiscovery.io -ec -silent -passive
projectdiscovery.io:443
projectdiscovery.io:2052
projectdiscovery.io:2082
projectdiscovery.io:2083
projectdiscovery.io:2087
projectdiscovery.io:2095
projectdiscovery.io:8443
projectdiscovery.io:80
```

### CODE REVIEW

**Review by ehsandeep — CHANGES_REQUESTED** [review]
We can add test with `-passive` option.

File: v2/pkg/runner/targets.go [hunk 1]
```diff
@@ -199,6 +205,14 @@ func (r *Runner) AddTarget(target string) error {
 	return nil
 }
 
+func joinHostPort(host, port string) string {
```
Comment (Mzack9999) [inline v2/pkg/runner/targets.go:208]: I think this is worth moving to `utils` with `TryJoinHostPort` or something similar, what do you think?

**Review by Mzack9999 — APPROVED** [review]

File: v2/pkg/runner/targets.go (hunk 1 above)
Comment (dogancanbakir) [reply v2/pkg/runner/targets.go:208]: Implemented in utils pkg https://github.com/projectdiscovery/utils/pull/255

**Review by ehsandeep — APPROVED** [review]
