### PR TITLE
remove skipped check

### LINKED ISSUE #1044: OnResult not be invoked when threshold reached
### Naabu version:
v2.3.0

### Current Behavior:

OnResult not be invoked when threshold reached

### Expected Behavior:

onresult can be invoked when threshold reached or provide options to choose wheather the onresult fun should be invoked when the ports threshold reached

### Steps To Reproduce:

1. add demo result fun in `v2/cmd/naabu/main.go`：
```
options.Stdin = false
	options.OnResult = func(result *result.HostResult) {
		gologger.Info().Msg("Hello")
	}
```
2. run with flag `-host 183.2.172.185 -pts 2`
image

3. Threshold reached but OnResult not be invoked

### PR DESCRIPTION
**Pull request by dogancanbakir**
Closes #1044

see repro steps at https://github.com/projectdiscovery/naabu/issues/1044
```console
$ go run . -host 183.2.172.185 -pts 2

                  __
  ___  ___  ___ _/ /  __ __
 / _ \/ _ \/ _ \/ _ \/ // /
/_//_/\_,_/\_,_/_.__/\_,_/

                projectdiscovery.io

[INF] Current naabu version 2.3.0 (latest)
[INF] Running CONNECT scan with non root privileges
183.2.172.185:80
183.2.172.185:443
[INF] Skipping 183.2.172.185 [ip], Threshold reached 
[INF] Found 2 ports on host 183.2.172.185 (183.2.172.185)
[INF] Hello
```

### CODE REVIEW

File: v2/pkg/result/results.go [hunk 1]
```diff
@@ -67,9 +67,6 @@ func (r *Result) GetIPsPorts() chan *HostResult {
 		defer r.RUnlock()
 
 		for ip, ports := range r.ipPorts {
-			if r.HasSkipped(ip) {
```
Comment (Mzack9999) [inline v2/pkg/result/results.go:70]: I've opted for a less invasive approach to add a Confidence field to the result struct, which is set Low in case the threshold is met

**Review by Mzack9999 — APPROVED** [review]
