### PR TITLE
fix: add DisableStdout option to suppress stdout output in SDK

### LINKED ISSUE #1414: SDK is always printing to stdout
### Naabu version:
v2.3.4 SDK

### Current Behavior:
When using the sdk i can't choose to not print results to stdout.
I have also tried to change logging levels with gologger with no luck.

### Expected Behavior:
I don't want the results to be printed to stdout, i want to print the results my self if needed to be printed.

### Steps To Reproduce:
```go
options := runner.Options{
		Host:     string[]{"netflix.com"},
		ScanType: "s",
		OnResult: func(hr *result.HostResult) {
			out <- hr
		},
		Ports:             "80,443",
		Verbose:           false,
		Rate:              500,
		Retries:           3,
		WarmUpTime:        2,
		Timeout:           2 * time.Second,
		Threads:           25,
		DisableStdin:      true,
		Debug:             false,
		Silent:            true,
		Stream:            true,
	}

	naabuRunner, err := runner.NewRunner(&options)
	if err != nil {
		log.Fatalf("Could not create a new naabu runner err: %v", err)
	}

	defer naabuRunner.Close()

	if err := naabuRunner.RunEnumeration(r.ctx); err != nil {
		log.Fatalf("Could not run naabu enumeration, err: %v", err)
	}
```

### PR DESCRIPTION
**Pull request by dogancanbakir**
## Summary
- Adds a new `DisableStdout` option to suppress stdout output when using the SDK
- Allows SDK users to handle results via `OnResult` callback without duplicate stdout printing

Closes #1414

## Usage
```go
options := runner.Options{
    Host:          []string{"example.com"},
    Ports:         "80,443",
    DisableStdout: true,
    OnResult: func(hr *result.HostResult) {
        // Handle result yourself
    },
}
```

## Test plan
- [x] Set `DisableStdout: true` in SDK usage
- [x] Verify no output is printed to stdout
- [x] Verify `OnResult` callback still receives results

## Summary by CodeRabbit

* **New Features**
  * Added a configuration option (can be enabled via the DISABLE_STDOUT environment variable) to suppress standard output, allowing integrations to consume results via callbacks or other channels without console output interference. Default behavior unchanged.

<sub>✏️ Tip: You can customize this high-level summary in your review settings.</sub>

### CODE REVIEW

File: pkg/runner/runner.go [hunk 1]
```diff
@@ -1094,12 +1096,14 @@ func (r *Runner) handleOutput(scanResults *result.Result) {
...
-					writer := csv.NewWriter(&buffer)
-					writer.Flush()
-					gologger.Silent().Msgf("%s", buffer.String())
+				if !r.options.DisableStdout {
+					if r.options.JSON {
+						gologger.Silent().Msgf("%s", buffer.String())
+					} else if r.options.CSV {
+						writer := csv.NewWriter(&buffer)
+						writer.Flush()
+						gologger.Silent().Msgf("%s", buffer.String())
```
Comment (knakul853) [inline pkg/runner/runner.go:1105]: seems `writer.Flush()`  redundant in new writer as nothing to flush, or we can use exiting writer than its fine,. though its not related to this pr  :)
